### ISSUE TITLE
XMLValidator not working on 4.0.0-beta.0

### ISSUE THREAD

**Issue by MarceloLuis1997** [NaturalIntelligence/fast-xml-parser#395]
* [x] Are you running the latest version?
* [X] Have you included sample input, output, error, and expected output? 
* [X] Have you checked if you are using correct configuration?
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)?

### Description
XMLValidator is not working on v4.0.0-beta.0, the `validate` function does not exists
### Input
```
import { XMLParser, XMLValidator } from 'fast-xml-parser'

export function validateXmlString (xml: string): boolean {
  try {
    return XMLValidator.validate(xml)
  } catch (error) {
    return false
  }
}
```

### Output
`Property 'validate' does not exist on type`

**Comment by amitguptagwl** [comment]
There was an issue with typings. So I had fixed that in 4.0.0-beta.1. Can you please check and let me know if you're still facing the issue

**Comment by MarceloLuis1997** [comment]
It's working fine in **4.0.0-beta.1**. Thank's!
