### ISSUE TITLE
Upgrade from 5.0.6 to 5.0.7 broke my build

### ISSUE THREAD

**Issue by faljse** [NaturalIntelligence/fast-xml-parser#736]
After upgrading from 5.06 to [5.0.7 ... 5.0.9] i cant use "X2jOptions" anymore:

`import {type X2jOptions, XMLParser} from 'fast-xml-parser';`
`error TS2305: Module '"fast-xml-parser"' has no exported member 'X2jOptions'.`

**Comment by amitguptagwl** [comment]
We added typings for cjs in v5.0.7 [commit](https://github.com/NaturalIntelligence/fast-xml-parser/commit/a9612d1628eaba9e47f21cf280284c0847f506ad)
But the typings for EMS module are still pointing to the old file. Unfortunately, I would not be able to check this before 4th Apr.

**Comment by amitguptagwl** [comment]
I tried this in my local. This is working fine. Can you please create a sample project or share the code that can help to debug?

```
import {
  XMLParser,
  XMLBuilder,
  XMLValidator,
  type X2jOptions,
  type XmlBuilderOptions,
  type validationOptions,
} from 'fast-xml-parser';

```

**Comment by amitguptagwl** [comment]
Please reopen the issue if you feel exist.
